<div id="main"></div>

<script src="src/content/js/jquery-3.6.0.min.js"></script>
<script src="vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="src/content/assets/datatables/datatables.min.js"></script>
<script src="src/content/assets/datatables/DataTables-1.11.3/js/dataTables.bootstrap5.min.js"></script>
<script src="src/content/assets/datatables/Scroller-2.0.5/js/dataTables.scroller.min.js"></script>

<script src="src/content/painel/js/app.js"></script>
<script src="src/content/painel/js/typefield.js"></script>